# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentop" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "0317b85c4b43cfa75e6439e14abd0141ec596cb1d8c065f9e65863dbecc6d176"
      url "https://github.com/pimlabs/agentop/releases/download/v#{version}/agentop_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0187368286bfeb579d4cebb1c641b1e765f1755b1fdb83e556062f83104da85"
      url "https://github.com/pimlabs/agentop/releases/download/v#{version}/agentop_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a679866d501eb3feca0b8452d364762aaa7f7773db0ef90fb97ddebfd4bee3d0"
      url "https://github.com/pimlabs/agentop/releases/download/v#{version}/agentop_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "72c99fe04bea4f3a994a38cea700d3c1b70486fb016dee761aff458b63e1be9f"
      url "https://github.com/pimlabs/agentop/releases/download/v#{version}/agentop_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentop"
  desc "TUI monitor for Claude Code multi-agent workflows"
  homepage "https://github.com/pimlabs/agentop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentop"]
    end
  end

  # No zap stanza required

end
