# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentop" do
  version "0.15.1"

  on_macos do
    on_arm do
      sha256 "bccb13b425ad05b4d78efac2e6b4df98c8980c82837a292ee39042931cc4ba9a"
      url "https://github.com/pimlabs/agentop/releases/download/v#{version}/agentop_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dad4c13e577a22e2afa2f2d0bfded85374f3516ebacc33f5952b7b8d6178013c"
      url "https://github.com/pimlabs/agentop/releases/download/v#{version}/agentop_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cbf100490ebfc146ddd081d317eb4f0880698e0f3f7a726749363d176fb8ec45"
      url "https://github.com/pimlabs/agentop/releases/download/v#{version}/agentop_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "13fcfcea04516d1bdc04aa1c14af88e30009f603e0620edb968f2af87c1787f4"
      url "https://github.com/pimlabs/agentop/releases/download/v#{version}/agentop_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentop"
  desc "TUI monitor for Claude Code multi-agent workflows"
  homepage "https://github.com/pimlabs/agentop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentop"]
    end
  end

  # No zap stanza required
end
