# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentop" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "b80f863177b5be50d8dbcc737863e6adc94107adbb123da9b8d70d8db25bf0de"
      url "https://github.com/pimlabs/agentop/releases/download/v#{version}/agentop_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bece8073a39957a73af37f5cc583c64e11e06b7eec41bbacd1947f70d14df286"
      url "https://github.com/pimlabs/agentop/releases/download/v#{version}/agentop_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "61fbf027733f2ac9ad43606d45c0b0bf1fd4c8468527714f0d34ba88cdda621e"
      url "https://github.com/pimlabs/agentop/releases/download/v#{version}/agentop_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e797ef9098493fd77edc343dc8d34703c90d5cccf0941f6fd94cdef514cbd55c"
      url "https://github.com/pimlabs/agentop/releases/download/v#{version}/agentop_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentop"
  desc "TUI monitor for Claude Code multi-agent workflows"
  homepage "https://github.com/pimlabs/agentop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentop"]
    end
  end

  # No zap stanza required

end
